notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

before_script:
  - xmllint --version

script: 'xmllint --noout --schema http://technical.openmobilealliance.org/tech/profiles/LWM2M.xsd ./reg/xml/*.xml'
